window:
  dimensions:
    lines: 48
    columns: 132

  padding:
    x: 26
    y: 26

  dynamic_padding: false
  startup_mode: Maximized

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    style: Retina
    family: "Fira Code Nerd Font"

  bold:
    family: "Fira Code Nerd Font"

  italic:
    family: "Fira Code Nerd Font"

  size: 11.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

custom_cursor_colors: true
draw_bold_text_with_bright_colors: false

bell:
  duration: 0
  color: "0xffffff"
  animation: EaseOutExpo

key_bindings:
  - { key: Back, chars: "\x7f" }
  - { key: F1, chars: "\x1bOP" }
  - { key: F2, chars: "\x1bOQ" }
  - { key: F3, chars: "\x1bOR" }
  - { key: F4, chars: "\x1bOS" }
  - { key: F5, chars: "\x1b[15~" }
  - { key: F6, chars: "\x1b[17~" }
  - { key: F7, chars: "\x1b[18~" }
  - { key: F8, chars: "\x1b[19~" }
  - { key: F9, chars: "\x1b[20~" }
  - { key: F10, chars: "\x1b[21~" }
  - { key: F11, chars: "\x1b[23~" }
  - { key: F12, chars: "\x1b[24~" }
  - { key: Insert, chars: "\x1b[2~" }
  - { key: Delete, chars: "\x1b[3~" }
  - { key: PageUp, chars: "\x1b[5~" }
  - { key: PageDown, chars: "\x1b[6~" }
  - { key: C, mods: Command, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: V, mods: Command, action: Paste }
  - { key: W, mods: Command, chars: "\x02&" }
  - { key: T, mods: Command, chars: "\x02c" }
  - { key: F, mods: Command, chars: "\x02/" }
  - { key: Up, mods: Alt, chars: "\x1b[1;3A" }
  - { key: Tab, mods: Shift, chars: "\x1b[Z" }
  - { key: Back, mods: Alt, chars: "\x1b\x7f" }
  - { key: Up, mods: Shift, chars: "\x1b[1;2A" }
  - { key: Down, mods: Alt, chars: "\x1b[1;3B" }
  - { key: Left, mods: Alt, chars: "\x1b[1;3D" }
  - { key: Up, chars: "\x1bOA", mode: AppCursor }
  - { key: Right, mods: Alt, chars: "\x1b[1;3C" }
  - { key: Up, mods: Control, chars: "\x1b[1;5A" }
  - { key: Up, chars: "\x1b[A", mode: ~AppCursor }
  - { key: End, chars: "\x1bOF", mode: AppCursor }
  - { key: Down, mods: Shift, chars: "\x1b[1;2B" }
  - { key: Left, mods: Shift, chars: "\x1b[1;2D" }
  - { key: Left, chars: "\x1bOD", mode: AppCursor }
  - { key: Right, mods: Shift, chars: "\x1b[1;2C" }
  - { key: Home, chars: "\x1bOH", mode: AppCursor }
  - { key: End, chars: "\x1b[F", mode: ~AppCursor }
  - { key: Down, chars: "\x1bOB", mode: AppCursor }
  - { key: Left, mods: Control, chars: "\x1b[1;5D" }
  - { key: Left, chars: "\x1b[D", mode: ~AppCursor }
  - { key: Right, chars: "\x1bOC", mode: AppCursor }
  - { key: Down, chars: "\x1b[B", mode: ~AppCursor }
  - { key: Down, mods: Control, chars: "\x1b[1;5B" }
  - { key: RBracket, mods: Command, chars: "\x02o" }
  - { key: LBracket, mods: Command, chars: "\x02;" }
  - { key: Home, chars: "\x1b[H", mode: ~AppCursor }
  - { key: PageUp, mods: Shift, chars: "\x1b[5;2~" }
  - { key: Right, mods: Control, chars: "\x1b[1;5C" }
  - { key: Right, chars: "\x1b[C", mode: ~AppCursor }
  - { key: PageUp, mods: Control, chars: "\x1b[5;5~" }
  - { key: PageDown, mods: Shift, chars: "\x1b[6;2~" }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~" }
  - { key: RBracket, mods: Command|Shift, chars: "\x02n" }
  - { key: LBracket, mods: Command|Shift, chars: "\x02p" }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Return, mods: Command, action: ToggleFullscreen }
  - { key: Minus, mods: Command|Shift, action: ResetFontSize }

mouse:
  hide_when_typing: true
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

selection:
  save_to_clipboard: false
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

debug:
  log_level: OFF
  ref_test: false
  render_timer: false
  print_events: false
  persistent_logging: false

import:
  - ~/.config/alacritty/themes/catppuccin.yml

env: 
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1"
