colors:
    primary:
        background: "#303446"
        foreground: "#C6D0F5"
        dim_foreground: "#C6D0F5"
        bright_foreground: "#C6D0F5"

    cursor:
        text: "#303446"
        cursor: "#F2D5CF"
    
    vi_mode_cursor:
        text: "#303446"
        cursor: "#BABBF1"

    search:
        matches:
            foreground: "#303446"
            background: "#A5ADCE"

        focused_match:
            foreground: "#303446"
            background: "#A6D189"

        footer_bar:
            foreground: "#303446"
            background: "#A5ADCE"

    hints:
        start:
            foreground: "#303446"
            background: "#E5C890"

        end:
            foreground: "#303446"
            background: "#A5ADCE"

    selection:
        text: "#303446"
        background: "#F2D5CF"

    normal:
        red: "#E78284"
        blue: "#8CAAEE"
        cyan: "#81C8BE"
        black: "#51576D"
        green: "#A6D189"
        white: "#B5BFE2"
        yellow: "#E5C890"
        magenta: "#F4B8E4"

    bright:
        red: "#E78284"
        blue: "#8CAAEE"
        cyan: "#81C8BE"
        black: "#626880"
        green: "#A6D189"
        white: "#A5ADCE"
        yellow: "#E5C890"
        magenta: "#F4B8E4"

    dim:
        red: "#E78284" 
        blue: "#8CAAEE" 
        cyan: "#81C8BE" 
        black: "#51576D" 
        green: "#A6D189" 
        white: "#B5BFE2" 
        yellow: "#E5C890" 
        magenta: "#F4B8E4" 

    indexed_colors:
        - { index: 16, color: "#EF9F76" }
        - { index: 17, color: "#F2D5CF" }
