colors:
    primary:
        background: "#1E1E2E" 
        foreground: "#CDD6F4"
        dim_foreground: "#CDD6F4"
        bright_foreground: "#CDD6F4"

    cursor:
        text: "#1E1E2E"
        cursor: "#F5E0DC"

    vi_mode_cursor:
        text: "#1E1E2E"
        cursor: "#B4BEFE"

    search:
        matches:
            foreground: "#1E1E2E"
            background: "#A6ADC8"

        focused_match:
            foreground: "#1E1E2E"
            background: "#A6E3A1"

        footer_bar:
            foreground: "#1E1E2E"
            background: "#A6ADC8"

    hints:
        start:
            foreground: "#1E1E2E"
            background: "#F9E2AF"

        end:
            foreground: "#1E1E2E"
            background: "#A6ADC8"

    selection:
        text: "#1E1E2E"
        background: "#F5E0DC"

    normal:
        red: "#F38BA8"
        blue: "#89B4FA"
        cyan: "#94E2D5"
        green: "#A6E3A1"
        white: "#BAC2DE"
        black: "#45475A"
        yellow: "#F9E2AF"
        magenta: "#F5C2E7"

    bright:
        red: "#F38BA8"
        blue: "#89B4FA"
        cyan: "#94E2D5"
        black: "#585B70"
        white: "#A6ADC8"
        green: "#A6E3A1"
        yellow: "#F9E2AF"
        magenta: "#F5C2E7"

    dim:
        red: "#F38BA8"
        blue: "#89B4FA"
        cyan: "#94E2D5"
        white: "#BAC2DE"
        green: "#A6E3A1"
        black: "#45475A"
        yellow: "#F9E2AF"
        magenta: "#F5C2E7"

    indexed_colors:
        - { index: 16, color: "#FAB387" }
        - { index: 17, color: "#F5E0DC" }

