[greenclip]
  static_history = []
  max_history_length = 50
  enable_image_support = true
  max_selection_size_bytes = 0
  blacklisted_applications = []
  trim_space_from_selection = true
  use_primary_selection_as_input = false
  image_cache_directory = "/tmp/greenclip"
  history_file = "/home/airscript/.cache/greenclip.history"
